version: '3.8'

services:
  vite-host:
    image: host:1
    container_name: vite-host
    env_file:
      - /.env.vite-host
    restart: unless-stopped
    networks:
      - proxy

  vite-catalog:
    image: catalog:1
    container_name: vite-catalog
    env_file:
      - /.env.vite-catalog
    restart: unless-stopped
    networks:
      - proxy
  
  vite-shopping:
    image: shopping:1
    container_name: vite-shopping
    env_file:
      - /.env.vite-shopping
    restart: unless-stopped
    networks:
      - proxy

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:2.12.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ../nginx_data:/data
      - ../letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
