FROM node:20-slim AS workspace

WORKDIR /app

COPY ../apps/vite-catalog/. apps/vite-catalog/.
COPY ../packages/. packages/.

RUN cd packages/store && npm ci
RUN cd packages/emitter && npm ci

RUN cd apps/vite-catalog && rm -rf node_modules && npm ci

RUN npm install -g concurrently

RUN cd apps/vite-catalog npm run build

EXPOSE 3007

CMD ["sh", "-c", "concurrently --kill-others \"cd packages/store && npm run watch\" \"cd packages/emitter && npm run watch\" \"cd apps/vite-catalog && npm run dev\""]